export const categories = [
    { id: 1, title: "Species" },
    { id: 2, title: "Gender" },
    { id: 3, title: "Status" },
    { id: 4, title: "Origin Location" },
    { id: 5, title: "Last Known Location" },
    { id: 6, title: "Location Type" },
    { id: 7, title: "Dimension" },
    { id: 8, title: "Episodes" }
];

export const customDescriptions = {
    "Rick Sanchez": "A genius scientist who has a troubled relationship with his family and often goes on adventures through space and other dimensions.",
    "Morty Smith": "A high school student who is frequently dragged into his grandfather Rick's adventures often serving as the moral compass of the duo.",
    "Summer Smith": "Morty's older sister who sometimes joins Rick and Morty on their adventures and struggles with typical teenage problems.",
    "Beth Smith": "Rick's daughter and a horse heart surgeon who has a complicated relationship with her father and her husband Jerry.",
    "Jerry Smith": "Beth's husband who often feels insecure about his place in the family and is generally disdained by Rick.",
    "Abadango Cluster Princess": "A member of the Abadango species who was originally captured by Rick and Morty but later helped them escape from a group of bounty hunters.",
    "Abradolf Lincler": "A genetic hybrid of Abraham Lincoln and Adolf Hitler created by Rick who ultimately meets a tragic end.",
    "Adjudicator Rick": "A member of the Galactic Federation who is responsible for investigating and enforcing laws across the universe.",
    "Agency Director": "The director of the Time Traveling Agency who often clashes with Rick and Morty.",
    "Alan Rails": "A ghost who possesses a ghost train and is a member of the Vindicators.",
    "Alexander": "A member of the Cromulon species who appears in the \"Get Schwifty\" episode.",
    "Alien Googah": "A member of an alien race who has a unique way of speaking.",
    "Alien Morty": "An alien who looks like Morty and is forced to live out his life as Morty.",
    "Alien Rick": "An alien who looks like Rick and is forced to live out his life as Rick.",
    "Amish Cyborg": "A cyborg who lives with a group of Amish people and joins Rick and Morty on an adventure.",
    "Annie": "A student at Morty's school who has a crush on him and later becomes an intern at the Smith family's horse hospital.",
    "Antenna Morty": "A Morty from an alternate dimension who has antennas on his head.",
    "Ants in my Eyes Johnson": "A salesman who is blind and has ants in his eyes.",
    "Armagheadon": "A giant creature that Rick and Morty encounter on a planet.",
    "Armothy": "A being made up of various arm pieces who was created by Rick.",
    "Arthricia": "A freedom fighter on a planet that was taken over by the Galactic Federation.",
    "Artist Morty": "A Morty from an alternate dimension who is an artist.",
    "Attila Starwar": "A character in a video game that Rick and Morty play.",
    "Baby Legs": "A cop who has baby legs due to a medical condition.",
    "Baby Poopybutthole": "A baby version of Mr. Poopybutthole who appears in a post-credits scene.",
    "Baby Wizard": "A wizard who is a baby.",
    "Bearded Lady": "A bearded lady who is part of a group of performers that Rick and Morty encounter.",
    "Bepisian": "A member of an alien race that is obsessed with a drink called Bepis.",
    "Beta-Seven": "A member of the Gearhead species who is a mechanic.",
    "Beth's Mytholog": "A creature created by Beth's imagination that comes to life and begins causing chaos in the real world.",
    "Birdperson": "A close friend of Rick's who is a skilled fighter and has a tragic past.",
    "Blim Blam": "An alien who Rick captures and puts on trial for eating his own offspring.",
    "Brad": "A man from a dimension where everyone has mantis-like features.",
    "Calypso": "A planet that Rick and Morty visit known for its powerful music.",
    "Chris": "A man from a dimension where humans have evolved to have long stretchy necks.",
    "Coach Feratu": "A vampire coach who is hired to help Morty improve at basketball.",
    "Conroy": "A butler who works for Rick and Morty in one of their adventures.",
    "Cornvelious Daniel": "An alien who poses as a simulation teacher to get information from Rick.",
    "Crocubot": "A cyborg crocodile who is a member of the Vindicators.",
    "Cromulons": "A giant alien species that appears in the 'Get Schwifty' episode.",
    "Cynthia": "An alien who appears in the 'Meeseeks and Destroy' episode.",
    "Davin": "A co-worker of Jerry's who has an affair with Beth.",
    "Diablo Verde": "A planet that Rick and Morty visit known for its deadly creatures.",
    "Diane Sanchez": "Rick's deceased wife whose memory haunts him throughout the series.",
    "Doofus Rick": "A Rick from an alternate dimension who is considered the 'least smart' Rick.",
    "Dream Aliens": "Aliens who invade people's dreams and try to steal their secrets.",
    "Dr. Glip-Glop": "A psychiatrist who is summoned by the family to help Jerry.",
    "Dr. Wong": "A family therapist who tries to help the Smith family with their issues.",
    "Duck With Muscles": "A duck that Rick gives human-like muscles to.",
    "Evil Morty": "A version of Morty who is revealed to be behind a plot to take down the Citadel of Ricks.",
    "Fart": "An alien who communicates through telepathy and is hunted by the Galactic Federation.",
    "Frankenstein's Monster": "A creature created by Rick and Morty using parts from dead people.",
    "Gazorpazorp": "A planet that Morty accidentally impregnates while on a sex robot adventure.",
    "Gearhead": "A species of aliens who are obsessed with cars and mechanics.",
    "Gene Vagina": "An alien who appears in the 'Interdimensional Cable' episodes.",
    "Giant Head": "A giant alien head that appears in the 'Mortynight Run' episode.",
    "Giant Testicle Monster": "A monster that Morty creates by accident in one of his adventures.",
    "Glexo Slim Slom": "A being from a planet that Rick and Morty visit known for its poisonous atmosphere.",
    "Gobo": "A creature that Morty befriends in the 'Close Rick-counters of the Rick Kind' episode.",
    "Goomby": "A creature that appears in the 'Pickle Rick' episode.",
    "Gwendolyn": "A woman who appears in the 'Mortynight Run' episode who is wanted by the Galactic Federation.",
    "Hemorrhage": "The leader of a group of rebels on a post-apocalyptic Earth.",
    "Jerryboree": "A daycare for Jerries from alternate dimensions.",
    "Jessica": "A girl from Morty's school who he has a crush on.",
    "Krombopulos Michael": "An assassin who is hired by Rick to kill someone.",
    "Levitation Crystal": "A crystal that Rick and Morty use to levitate objects.",
    "Birdperson": "A close friend of Rick's who is a skilled fighter and has a tragic past.",
    "Blim Blam": "An alien who Rick captures and puts on trial for eating his own offspring.",
    "Brad": "A man from a dimension where everyone has mantis-like features.",
    "Calypso": "A planet that Rick and Morty visit known for its poisonous atmosphere.",
    "Gobo": "A creature that Morty befriends in the 'Close Rick-counters of the Rick Kind' episode.",
    "Goomby": "A creature that appears in the 'Pickle Rick' episode.",
}